name: Sync Maestro Postman Collection

on:
  push:
    branches:
      - demo  # Change this to the branch you want to trigger the action
    paths:
      - 'assets/maestro-collection.json'

jobs:
  update-postman:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update Maestro Postman Collection
      env:
        POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
      run: |

        # Run the Postman API to update the collection
        GITHUB_COLLECTION_PATH="./assets/maestro-collection.json"
        COLLECTION_UID=${{ vars.MAESTRO_COLLECTION_UID }}
        
        # Read the file content and wrap it inside a collection object
        WRAPPED_CONTENT=$(jq -n --argfile data "$GITHUB_COLLECTION_PATH" '{"collection": $data}')
        
        # Write the wrapped content to a temporary file
        echo "$WRAPPED_CONTENT" > wrapped_collection.json
        
        # Use curl with --data-binary to handle large file content
        curl --location --request PUT "https://api.getpostman.com/collections/$COLLECTION_UID" \
             --header "x-api-key: $POSTMAN_API_KEY" \
             --header "Content-Type: application/json" \
             --data-binary @wrapped_collection.json
